<?php

namespace LWMIS\GenerateDocument;

class ExtendTCPDF extends \TCPDF
{
  public function __construct(string $page_size = 'A4')
  {
    parent::__construct(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);
    $this->setCreator('Labour Welfare Board');
    $this->setAuthor('Sriram Bala');
    $this->setTitle('TNLWB');
    $this->setSubject('Labour Welfare Board -TNLWB');
    $this->setKeywords('Labour Welfare, TNLWB, LWMIS, Payment');
    $this->setHeaderFont(array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
    $this->setFooterFont(array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));
//    $this->setAutoPageBreak(true, 25);//same as PDF_MARGIN_BOTTOM
    $this->setAutoPageBreak(true, PDF_MARGIN_BOTTOM);
    $this->setImageScale(PDF_IMAGE_SCALE_RATIO);
    $this->setFontSubsetting(true);
    $this->setFont('times', '', 14, '', true);
//    $this->setPrintHeader(false);//to disable header line
//    $this->setPrintFooter(false);//to disable footer line
//    var_dump('Page S====',$page_size);
    $this->AddPage('P', $page_size, true);
    $this->SetFooterMargin(PDF_MARGIN_FOOTER); // 25

    if ($this->getPage() == 1) {
      $this->SetFont(PDF_FONT_NAME_MAIN, 'B', 18);
      $this->Cell(0, 0, 'Tamil Nadu Labour Welfare Board.', 0, 2, 'C', false, '', 0, false, 'T', 'C');
      $this->SetFont('times', '11', 10);
      $this->Cell(0, 0, 'P.B No. 718, DMS Compound, Anna Salai, Teynampet, Chennai - 600 006.', 0, 2, 'C', false, '', 0, false, 'T', 'C');
      $this->Line(10, 24, $this->getPageWidth() - 10, 24);//<- remove this if there is a problem in lining.
    }

  }

  public function Header(): void
  {
    parent::Header(); // TODO: Change the autogenerated stub
    /*$file = __DIR__.'/tnEmblemTransparent.png';
    $this->setAlpha(0.2);
    $this->Image($file, 8, 10, 223, 280, '', '', 'C', false, 300, '', false, false, 0);*/

//    $this->Line(10, 10, $this->getPageWidth() - 10, 10);//top line
    $this->Line($this->getPageWidth() - 10, 10, $this->getPageWidth() - 10, $this->getPageHeight() - 10);//right line
//    $this->Line(10, $this->getPageHeight() - 10, $this->getPageWidth() - 10, $this->getPageHeight() - 10);//bottom line
    $this->Line(10, 10, 10, $this->getPageHeight() - 10);//left line

  }


}
